### ISSUE TITLE
Database scripting service. Set Date, Time, Timestamp

### ISSUE THREAD

**Issue by ViktorMarinov** [dirigiblelabs/core_api#39]
https://github.com/dirigiblelabs/core_api/blob/master/core_api/ScriptingServices/db/database.js

In functions statementSetDate, statementSetTime, statementSetTimestamp

java.util.Date,  java.util.Time,  java.util.Timestamp
should be
java.sql.Date, java.sql.Time, java.sql.Timestamp

**Comment by delchev** [comment]
Thanks Viktor!
Fix is provided with the commit above!
