### ISSUE TITLE
session

### ISSUE THREAD

**Issue by delchev** [dirigiblelabs/core_api#5]
API for 'session'

**Comment by delchev** [comment]
/* globals $ */
/* eslint-env node, dirigible */

var response = require('api/response');
var session = require('api/session');

session.setAttribute("attr1", "value1");
var attr = session.getAttribute("attr1");

response.println("[Attribute]: " + attr);
response.flush();
response.close();

**Comment by delchev** [comment]
Included methods
====

getAttribute(name) 
getAttributeNames() 
getCreationTime()
getId() 
getLastAccessedTime() 
getMaxInactiveInterval() 
invalidate() 
removeAttribute(name) 
setAttribute(name, value) 
setMaxInactiveInterval(interval)

**Comment by ThuF** [comment]
Source: https://github.com/dirigiblelabs/core_api/blob/master/core_api/ScriptingServices/api/session.js

Tested with:

- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/session/session_attribute_test.js
- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/session/session_attribute_names_test.js
- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/session/session_remove_attribute_test.js
- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/session/session_info_test.js
- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/session/session_invalidate_test.js
