### ISSUE TITLE
globals

### ISSUE THREAD

**Issue by delchev** [dirigiblelabs/core_api#7]
API for "globals"

**Comment by delchev** [comment]
Usage
====

/* globals $ /
/ eslint-env node, dirigible */

var response = require('api/response');
var globals = require('api/globals');

globals.set("attr1", "value1");
var attr = globals.get("attr1");

response.println("[Attribute]: " + attr);
response.flush();
response.close();

**Comment by delchev** [comment]
Methods
====
clear()
containsKey(key)
containsValue(value)
get(key)
isEmpty()
keys()
set(key, value)
remove(key)
size()
values()

**Comment by ThuF** [comment]
Source: https://github.com/dirigiblelabs/core_api/blob/master/core_api/ScriptingServices/api/globals.js

Tested with:
- https://github.com/dirigiblelabs/core_api/blob/master/core_api/TestCases/api/globals_test.js
